### ISSUE TITLE
Tiles: Tile images should use link field for linking to

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#105]
## Overview
The current paragraph Tiles element is linking the image to the media value, but should instead link to the link field in the tile. 

![fullscreen_9_12_17__4_01_pm](https://user-images.githubusercontent.com/179803/30352223-bbc0af20-97d3-11e7-910a-9dc28c97ebf5.png)

**Comment by juliaford** [comment]
@tauno @mshaver the "add tile" feature in content currently has two options, "add tile" or "add tiles." The only difference that I see between the two is the "add tile" button at the bottom of the previous tile when your initial selection is "add tiles." Can't we eradicate add Tile?

**Comment by mshaver** [comment]
@juliaford, when you first select "Add Tiles" as a content area, it defaults to only one "Tile" to begin with. To continue to add additional "Tiles", you have to have the "Add Tile" button. This way you can add 3 or more of these to round out the layout of that content. I'm sure some help text here would be useful!

**Comment by juliaford** [comment]
@mshaver Right I know!  What I was referring to I seriously can not freaking duplicate now, so something changed in the last two minutes. I will take it.

**Comment by juliaford** [comment]
Ok @mshaver I replicated this issues. If you are editing or creating an event or news item and adding a feature this is the drop down: 
<img width="275" alt="screen shot 2017-09-15 at 10 12 29 am" src="https://user-images.githubusercontent.com/28023410/30494925-d506e90e-99fe-11e7-9c02-4a817d17084a.png"> let's fix it!

**Comment by mshaver** [comment]
Nice find @juliaford! I'm going to split this bug into it's own issue.

**Comment by tauno** [comment]
@heypaxton This looks like a good item to implement in the twig template for the tile. I noticed that both the child theme and the parent theme have twig templates for the tile paragraph type in the CORI repo. I was hoping we wouldn't need separate twig templates for each child theme. Are there differences between FRGK and CORI templates?

**Comment by heypaxton** [comment]
@tauno there is one difference. The source order of the lead text is different in each theme. 
<img width="398" alt="screen shot 2017-09-20 at 2 53 40 pm" src="https://user-images.githubusercontent.com/543800/30669561-9fc85200-9e13-11e7-9644-a76f3259be95.png">
![screen shot 2017-09-20 at 2 53 56 pm](https://user-images.githubusercontent.com/543800/30669560-9fc441ba-9e13-11e7-93d0-31e37c6a0580.png)

**Comment by mshaver** [comment]
@heypaxton, @tauno, @vickibrown; I wonder if we're making the Tiles paragraph fields too prescriptive? I thought we had originally said the title, text and any dates, etc were going to be handled in the single text area? Right now we have:
* Image
* Lead
* Title
* Text
* Link

Do you think we should simplify this a bit?

**Comment by tauno** [comment]
@heypaxton I copied the CORI template into bene_base and tweaked it to link the image and title to the link url.

@mshaver The variable date placement is the only piece I'm concerned about here. Title separate lets us enforce proper markup for that field (should be an h tag) and link it to the link url if one is provided. We could fairly easily make "Date placement" in tiles a configuration option and change the order of the output based on that so we don't need to have separate templates.

**Comment by vickibrown** [comment]
@mshaver I agree these should be flexible. They will sometimes just be used to display CTAs or listed content, rather than events or news items.

**Comment by tauno** [comment]
If title is a fixed field, our only option to keep it flexible would be to drop the lead field and that would always come after the title as part of the text area.

**Comment by mshaver** [comment]
@tauno, I think that would make sense. They can always exclude the Title field value and order it different in the WYSIWYG as well? But removing the lead field seems to make it simpler. I'd say the same for the link field; if there is a value, it shows up under the text field.

**Comment by tauno** [comment]
Based on the slack discussion I created #119.
