### ISSUE TITLE
Text Formats: Consistent text formats across text fields

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#106]
## Overview
It looks like we have some inconsistency across some of the text fields and would be good to make sure we are set for these going forward. Here is what I'd recommend and what is currently set for each:

## Basic HTML
- [x] `/admin/structure/types/manage/event/fields/node.event.bene_intro` uses "Basic HTML"
- [x] `/admin/structure/types/manage/news/fields/node.news.bene_intro` uses "Basic HTML"
- [x] `/admin/structure/paragraphs_type/rich_text/fields/paragraph.rich_text.field_text` uses "Basic HTML"
- [x] `/admin/structure/types/manage/page/fields/node.page.bene_intro` uses "Restricted HTML" and "Full HTML". **Remove "Full HTML"**
- [ ] `/admin/structure/paragraphs_type/tile/fields/paragraph.tile.field_text` uses "Restricted HTML". **Swap for "Basic HTML"**

**Roles:** Staff, Staff Admin, Administrator

**Bugs:**
- [ ] The alignment buttons are not showing up for Basic HTML format
- [x] Add "Source" button

## Restricted HTML
- [x] `/admin/structure/paragraphs_type/feature_full_width/fields/paragraph.feature_full_width.field_text` uses "Restricted HTML"

**Roles:** Staff, Staff Admin, Administrator

**Comment by tauno** [comment]
@mshaver Alignment looks correct on Basic - did you mean Restricted? I added those options there. The only difference between Basic and Restricted now is the embed functionality. I'm inclined to leave the Tile text area as restricted to avoid issues with big images, videos, etc getting uploaded into that area.

**Comment by mshaver** [comment]
@tauno, thanks for making these consistent. Yes, I might have mixed the alignment issues.
