### ISSUE TITLE
Max width not set for feature paragraph and block-hero FRGK/CORI

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#109]
## Overview
The right side of the feature paragraph block extends beyond the max width of the page elements:
![title-hero](https://user-images.githubusercontent.com/179803/30353486-0e2ab1e6-97db-11e7-9fde-e4a7f8f771b1.png)

Add `max-width: 1800px;` to the following:
- [ ] `.paragraph--type--feature-full-width`
- [ ] `.block-hero`

**Comment by heypaxton** [comment]
This was fixed by removing the max width from the site wrapper. Blocks are able to go full width and align correctly now.
