### ISSUE TITLE
FRGK - responsive blocks

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/bene#126]
## Overview
Blocks look good on desktop but need adjustments at mobile. These comments are just for mobile.
## This ticket is done when:

**Homepage Hero**
- [x] Small text on top should be 16 pixels, 20 pixel line height
- [x] Headline text (2nd line of text) should be 32 pixels, 40 pixel line height

**Full-width CTA blocks**
- [x] Headline should be 32 pixels, 40 pixel line height
- [x] Body text should be 16 pixels, 25 pixel line height

**Padding**
- [x] Blocks should have 75 pixels of padding on the top and bottom of each block

**Comment by juliaford** [comment]
@heypaxton to you!
