### ISSUE TITLE
Editing box for images is cut off 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#130]
## Overview
![screen shot 2017-09-21 at 9 36 33 pm](https://user-images.githubusercontent.com/28023410/30729506-040869ba-9f15-11e7-98c8-e8931261a6a4.png)

You can't see the top of the editing/upload box on anything less than a full width big browser. ^

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by heypaxton** [comment]
This has been added to `8.x-1.x` branch.
