### ISSUE TITLE
wysiwyg styled text doesn't center align 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#131]
## Overview
If I center text in the into wysiwyg the header styled text stays right aligned while the normal text does what I want it to. 
![screen shot 2017-09-21 at 9 53 33 pm](https://user-images.githubusercontent.com/28023410/30729854-7050fde2-9f17-11e7-8b87-ae991f2e221e.png)

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by tauno** [comment]
Do we want to allow centering headings or should this just be styled in CSS for the home page?

**Comment by juliaford** [comment]
We want to allow

Julia

**Comment by tauno** [comment]
In 5c73316
