### ISSUE TITLE
CORI - Typography Styles

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/bene#133]
## Overview
The type styles need a little refinement.

## This ticket is done when:
- [x] Intro Copy Should be Open Sans regular, not light
- [x] H3 shouldn't be all caps
- [x] Check tracking on H4, it looks tracked out and shouldn't be
- [x] H5 should be Open sans bold, 18 pixels, 24 pixel line height. Hex #064075
- [x] Body text in cards should be Open sans regular 15 pixels, 25 pixel line height, Hex #000000
- [x] Block quote styling currently off. Placeholder to fix it.
- [x] Inner page header should stay centered when it's responsive
- [x] Sub menu links need 3x the space between items

**Comment by juliaford** [comment]
@heypaxton H5 should be blue, @vickibrown looking to you for hex.

**Comment by vickibrown** [comment]
@juliaford Hex #064075
