### ISSUE TITLE
Footer: allow additional HTML tags in footer fields

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#136]
## Overview
The footer fields will likely need a bit more customization by clients and so will need more HTML ability. You can see an issue here where the `<br />` are not rendered and it's hard to get a unique hours display to work. 

<img width="414" alt="faqs___free_geek" src="https://user-images.githubusercontent.com/179803/30766690-ae5399bc-9fab-11e7-8a33-b818ec2ce79d.png">

**Comment by tauno** [comment]
Fixed by allowing br in restricted and basic editors: 6aeff60
