### ISSUE TITLE
Newsletter: Child theme hover for external newsletter link button

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#137]
## Overview
External link button needs child theme styling or to have colors defined in variables correctly in parent theme? 

<img width="946" alt="fullscreen_9_22_17__3_38_pm" src="https://user-images.githubusercontent.com/179803/30766790-655db214-9fac-11e7-9ccd-8bf78488249d.png">

**Comment by juliaford** [comment]
https://drive.google.com/file/d/0BwQyBnwBPTw1Yml0TFRvYWNkSVk/view?usp=sharing
FRGK noticed a delay here? Check out their video capture of the problem. @tauno @heypaxton

**Comment by heypaxton** [comment]
Added fix for this.
