### ISSUE TITLE
FRGK: Focal point not applying 

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#138]
## Overview
The focal point changes for FRGK are not being applied and so changing the focal point has no effect. You can see this in action here: 

FRGK not working:
* https://live-frgk.pantheonsite.io/who-we-are
* https://live-frgk.pantheonsite.io/

CORI working:
* https://live-cori.pantheonsite.io/campaigns

**Comment by tauno** [comment]
@mshaver Looks like FRGK is correctly cropping to the bottom of the image - that's where the focal point it. Are you seeing something different? Might be the image style needed to get flushed.

**Comment by mshaver** [comment]
@tauno, strange? Take a look at the home page hero here: https://live-frgk.pantheonsite.io/

The focal point for that image is set to the middle now, but it's still being offset. Maybe it's just the horizontal focal point that isn't working right now, but the vertical one is?

**Comment by tauno** [comment]
I think the width of the original image is making it so it can't center on the faces. Note the line on the wall on the far left.

Original: 
https://live-frgk.pantheonsite.io/sites/default/files/Free%20Geek%20Another%20Look%2009.10.15-62.jpg?itok=a04gZAnJ

Cropped:
https://live-frgk.pantheonsite.io/sites/default/files/styles/homepage_hero_xl/public/Free%20Geek%20Another%20Look%2009.10.15-62.jpg?itok=a04gZAnJ

**Comment by mshaver** [comment]
Thanks @tauno, I see, so is there a size for the hero or interior subpages that we should recommend for uploading?

**Comment by tauno** [comment]
@mshaver and @juliaford I deployed an update to the focal point module that hopefully resolved this. Adjusting the focal point should now properly clear the cached images. We'll want to keep an eye on it to be sure.
