### ISSUE TITLE
FRGK: Font sizes and iframes

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#143]
Font sizes are seem to be very different between numbered and bulleted lists
iFrame embeds don't stick when I paste into the source editor

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by heypaxton** [comment]
I think iframes are being stripped from the wysiwyg most likely. @tauno can we allow iframes in the RTE for users?

**Comment by heypaxton** [comment]
Fixed list item font size.

**Comment by tauno** [comment]
Iframes are in a separate ticket but should work only when in Full HTML input mode.
