### ISSUE TITLE
Benesubnavigation disappears at 3rd level

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#151]
## Overview
It appears the third level subnavigation disappears at the 3rd level. You can see this happening on the following page on FRGK: https://live-frgk.pantheonsite.io/ways-give/donate-technology

**Comment by tauno** [comment]
@mshaver Have you seen this on other pages? It looks like that link exists in both the utility nav and the main nav. I'm guessing the sub nav code is using the utility nav first. Perhaps we can switch the order around, but ultimately it'll just default to one of the instances of that link and use that to render the siblings or children.

**Comment by mshaver** [comment]
@tauno, interesting! That's why it was inconsistent. I thought it was some other thing causing it. Now I see it also happening for https://live-frgk.pantheonsite.io/ways-give/volunteer. So are the options to only look to the main menu for siblings and children? I imagine we're going to have this happen a fair amount since the utility nav is frequently used to supliment deeper sections or pages in the site.

**Comment by tauno** [comment]
Got a fix for this - at least an interim one. Currently where there are multiple links for the same url/route we use the first one found - this is the shallowest link. I switched it now use the deepest link. Not a perfect system but it seems more likely to work than the current approach. Another alternative might be to make the duplicate utility link a full url.

**Comment by mshaver** [comment]
@tauno Looks like the interim solution here is still causing problems for FRGK. I wonder if we should only look at the main menu for these? That might be an assumption for most sites, but it does seem like most will have child menus in the main nav and single depth menu items in other menus?

**Comment by tauno** [comment]
@mshaver See https://d842-frgk.pantheonsite.io/ways-give/volunteer for the new behavior. We get a breadcrumb, but there is still odd behavior in the active link highlighting since this link exists in at least 3 places (utility and two spots in the main nav).

**Comment by mshaver** [comment]
@juliaford @tauno, I ended up fixing this with a simple trick to link to a redirect to the actual page. So under Community Programs, the "Volunteer" link now links to /volunteer which then redirects to /ways-to-give/volunteer. Very easy and a good model if this issue comes up again in the future. @juliaford can you be sure to notify the client about this?
