### ISSUE TITLE
FRGK Polish Requests

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#153]
## Overview

**Typography**
ULs: Not sure if it's by design, but our regular paragraph body content is #000 black, and <ul> is in #5C5B5B. Could we have everything the same color? 

H2s: Multi-line H2 line-height feels too tight. Right now it's set at 2.375rem, what do you think about bumping that up slightly?

**Button Size**
The a.button style has a size of 0.75rem, which makes it weirdly smaller than all of the body copy. Can we make it the same size as the copy? 

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by heypaxton** [comment]
This fix has been deployed to the live environment.
