### ISSUE TITLE
FRGK: Child menus disappearing

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#154]
## Overview
Affected components: The child menus are disappearing for certain titles if you click on any option within them more than once.   

Description: For example, if you click on the Plug into Portland page, go there, and then click again the button for Plug into Portland, the entire menu will vanish. I'd like that not to happen.

Browser/Device: Tested on Chrome and Safari, when I tried it on Chrome it actually opened it in a new window.

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by tauno** [comment]
Looks like a theming/js error @heypaxton since what's happening is `display:none` is getting applied to the child/sibling items.

**Comment by heypaxton** [comment]
This fix has been deployed to the live environment.
