### ISSUE TITLE
FRGK: Re-Emergence Child Menus Disappearing

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#155]
## Overview
Affected components: The child menus are disappearing for certain titles if you click on any option within them. 
Description: For example, if you click on "Community Programs" and then "Volunteer," when you are on the "Volunteer" page, the child menu containing other options within "Community Programs" will disappear. I would like the menu to remain even when someone is on the other individual pages within the category.     
<img width="753" alt="screen shot 2017-11-08 at 4 49 40 pm" src="https://user-images.githubusercontent.com/28023410/32582774-49fff14e-c4a5-11e7-886e-252ea7706ff0.png">
<img width="796" alt="screen shot 2017-11-08 at 4 49 45 pm" src="https://user-images.githubusercontent.com/28023410/32582776-4d07d1c2-c4a5-11e7-96ef-7a170c8dddf7.png">

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mshaver** [comment]
Let's close this issue and reopen #151 since it has some good history of the issue. It does appear to be the same issue.
