### ISSUE TITLE
CORI: Bullets and alignment are off 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#157]
## Overview
Example page: https://live-cori.pantheonsite.io/en-espanol

This is what the live page looks like:
![this is what it looks like live](https://user-images.githubusercontent.com/28023410/32902995-bc2b689e-caa8-11e7-8a1f-499ed0819410.png)
This is what the wysiwyg editor looks like:
![this is what i see](https://user-images.githubusercontent.com/28023410/32903008-c364e4f0-caa8-11e7-9189-8c518425e793.png)

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by heypaxton** [comment]
These bullets had `<p>` tags inside the `<li>` tags. I removed the paragraph tags and now the bullets are back to normal.

<img width="803" alt="screen shot 2017-11-16 at 3 12 06 pm" src="https://user-images.githubusercontent.com/543800/32921058-dc8ddec2-cae0-11e7-8ad0-796be09a731e.png">
