### ISSUE TITLE
WRI: Child menu items on mobile not showing up

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#166]
<img width="427" alt="bene-child-menu-items-mobile" src="https://user-images.githubusercontent.com/179803/34750020-75b6ccd8-f559-11e7-830e-805ff7e66067.png">

**Comment by komejo** [comment]
Fixed (By Eric) and now on test with refreshed content from live: https://test-wri-bene.pantheonsite.io/partner-us

**Comment by mshaver** [comment]
@komejo, just a small tweak for this to make it perfect. Remove `margin-right` on mobile items. They currently are offset, making them look a bit strange. 

![wri-mobile-menu](https://user-images.githubusercontent.com/179803/35783876-f1adc318-09c3-11e8-9831-96a6e897acb6.png)

**Comment by komejo** [comment]
Fixed.

**Comment by komejo** [comment]
On test!

**Comment by mshaver** [comment]
Nice!

**Comment by mshaver** [comment]
@komejo, it looks like the solution here might have affected the behavior of the normal child menu on the desktop views. You can see the issue by following these steps:

* Visit: https://live-wri-bene.pantheonsite.io/partner-us
* Select "Meet our partners": https://live-wri-bene.pantheonsite.io/partner-us/meet-our-partners
* Select "Partner with Us"

You'll see that it does not take you back to the https://live-wri-bene.pantheonsite.io/partner-us page even though the URL does change. It also hides the child menu item.

**Comment by komejo** [comment]
Added mobile detection and refactored the toggle to be a bit smarter. On test: https://test-wri-bene.pantheonsite.io/partner-us/meet-our-partners

**Comment by mshaver** [comment]
@komejo, this is working well. It's possible this is an issue on https://live-cori.pantheonsite.io/columbia/your-fish-toxic as well and possibly frgk. At this point we should only handle CORI's issue. Why don't we keep this ticket open and handling those two projects as well. Was this child theme related or parent? 

- [x] CORI menu behavoir

**Comment by komejo** [comment]
@mshaver We didn't implement any submenu handling in the Bene base theming as far as I know, so these are child theme related. It looks like the CORI menu got implemented first and then copied over to WRI, but b/c of the way the navigation works it's OK on CORI and was off on WRI.

**Comment by komejo** [comment]
Added the mobile wrapper and pushed to test.

**Comment by mshaver** [comment]
Hi @komejo, this seems to work great on https://test-cori.pantheonsite.io/. Looping in @juliaford to see if she'd like to go ahead and push live. @juliaford, this fixes https://redbooth.com/a/#!/projects/1825355/tasks/35342389.

**Comment by mshaver** [comment]
@komejo for whatever reason, this isn't working again on WRI?

**Comment by komejo** [comment]
Looks like this was a temp/caching issue? There's still an issue with the mobile menus only showing the 1st child-menu item, let me know if you'd like that fixed, it's very simple.

**Comment by mshaver** [comment]
@komejo It would be great to fix if you can. We're launching on Friday! I know this takes away from LVHN, but I'll let Rose know.

**Comment by mshaver** [comment]
Looks great!
