### ISSUE TITLE
Bene: Link footer logo to home page

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#167]
## Overview
The footer logo should also link to the home page of the site, similar to the header logo. This can be generically for Bene, but the request has come from WRI. 

## Dev
- [x] Wrap footer logo to link to home page

**Comment by komejo** [comment]
This is WRI-only as the bene design has no logo in the footer. Done.

**Comment by mshaver** [comment]
@komejo, I'm not seeing this one for some reason? I also see that it might be difficult since the logo is actually a background image? We might need to shelve this one.

**Comment by mshaver** [comment]
Now I'm seeing this! Nice work!
