### ISSUE TITLE
Bene: Contain contact forms within body width

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#168]
## Overview
The contact forms are currently not contained within the bene body width. Most sites will use the standard contact us contact form, but many could add additional forms. It will be important to not make this specific to just the contact us form. 

![wri-contact-form.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/1bb4bc87-fe3e-47d2-83c1-31022c6b3599)

**Comment by komejo** [comment]
Updated bene-base in both the WRI implementation and Bene.

**Comment by mshaver** [comment]
Looks good!
