### ISSUE TITLE
WRI: Inline body link style

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#170]
## Overview
The inline body link style is deferring to the standard bene link style on WRI. You can see it on this page: https://live-wri-bene.pantheonsite.io/about-us

Currently:
![wri-body-link-style.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/a2891000-4542-4b9c-aab4-f4945a82ec13)

Change to:
![wri-body-link-style2.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/27482159-1336-4ce1-a7d1-537a885adf4a)

**Comment by komejo** [comment]
Added ckeditor stylesheet for WRI child theme.

**Comment by mshaver** [comment]
Looks good @komejo!
