### ISSUE TITLE
WRI: Tiles link text style below text

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#171]
## Overview
The tiles paragraph type has a "Link" that admins can add as a prompt to lead users to the pages where the tiles are intended to go. The WRI designs didn't include a style for these, so they were not themed. 

You can see what it looks like on the staging site here: 
https://live-wri-bene.pantheonsite.io/our-future

![wri-link-text-style-tiles.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/46eb7b4d-cf43-423f-80b6-1815a1614ee2)

## Design
- [x] Provide design for link text: style same as body link style.

## Theme
- [ ] Theme same as body link style

**Comment by sarahvleigh** [comment]
@mshaver, are there no buttons enabled for tiles? If not, I believe the most reasonable thing to do from a UX perspective would be to adopt established link styles. I believe that's just an underline of the linkable text.

**Comment by mshaver** [comment]
@sarahvleigh, I think that makes the most sense rather than an explicit button. The user could add a button if they wanted to the text above, but we also wanted to provide a easy link button on the tile as well. Here is the admin side of an individual tile:
![wri-tiles](https://user-images.githubusercontent.com/179803/35112500-18246388-fc33-11e7-8a83-084c95eea84b.png)

**Comment by sarahvleigh** [comment]
@mshaver noted. I would say that in these instances, the more enticing and specific the language, the better chances for a click. "See how we're planning for the future" is more interesting than "Browse".

**Comment by mshaver** [comment]
@sarahvleigh, did you have any more thoughts regarding the tile link style? If it's just the normal body link style, we can make that change. Or we can change to something more specific to tiles if you have thoughts there.

**Comment by sarahvleigh** [comment]
@mshaver Given that the copy may be really short (one word) or as long as a sentence, let's try the body link style. I don't think it merits a third font size within one tile. And apologies, thought this was issue closed! Lemme know if you are wanting to explore this further!

**Comment by mshaver** [comment]
Thanks @sarahvleigh!

**Comment by komejo** [comment]
Done - was partially implemented, just needed higher child-theme specificity.

**Comment by mshaver** [comment]
Looks great!
