### ISSUE TITLE
WRI: Focal point not working on fresh install of Bene, as seen for WRI

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#172]
## Overview
The focal point module isn't working on the WRI site and wasn't on initial site build. This could be an issue with the build that would should address in Bene in general. 

The more immediate need is to address for WRI specifically so they can continue to stage content. 

## Dev
- [ ] debug focal point not showing up on images

**Comment by ruscoe** [comment]
Notes:

* Focal Point module is enabled
* Tile-M, Tile-S, Tile-L image styles are using Focal Point Scale and Crop effect

Changed:

* Set image media form display widget to "Image (Focal Point)"

**Comment by mshaver** [comment]
This looks good @ruscoe! Thanks for figuring out!
