### ISSUE TITLE
WRI: Tiles vertical spacing

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#173]
## Overview
The tiles paragraph type can accommodate more than 3 tile elements being added and when that happens the 4th item will wrap and be below the first 3. We need to provide padding to the tile elements so they don't bump into each other if this happens. 

You can see this happening on the following page:
https://live-wri-bene.pantheonsite.io/river-stories

![wri-tiles-spacing.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/e167bd9f-afdc-4baa-a2bd-b5582be46fde)

**Comment by komejo** [comment]
Looks like this has been addressed with help text: `Add additional tiles with the “Add Tile” button. (Recommendation: place tiles in sets of three and not to exceed 6 total, or two rows, of tiles)`, but I've moved some of the spacing the the tiles instead of the wrapper so tablet and mobile sizes look more uniform.

**Comment by mshaver** [comment]
@komejo, those are looking better for sure. I did notice that the space between rows seems quite large now. It also looks like the equal heights code is not reacting with the text very well. You can see in this screenshot at a tablet size. 

![river_stories___willamette_river_initiative](https://user-images.githubusercontent.com/179803/35746205-e8c183e0-07fa-11e8-830c-d8116c34859a.png)

**Comment by komejo** [comment]
Fixed the equal heights function (added a reinit on resize)  and evened out the spacing.

**Comment by mshaver** [comment]
@komejo, not sure if this regression was related to the tiles work, but it looks like we introduced a white background on the site? If you look at the live site you can see there is a transparent black, which creates a nice gray on the main body content region. 

![river_stories___willamette_river_initiative](https://user-images.githubusercontent.com/179803/35783921-181a2b12-09c5-11e8-8325-3ccb1b3aad8b.png)

**Comment by komejo** [comment]
@mshaver I was wondering about that! Happy to remove it.

**Comment by mshaver** [comment]
Looking great!
