### ISSUE TITLE
WRI: Inline image padding below headers

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#178]
## Overview 
It appears that the inline images added by the WYSIWYG editor do not have any margin-top and so don't align well with the paragraph floated next to it. You can see an example here: 
https://live-wri-bene.pantheonsite.io/partner-us/meet-our-partners

It doesn't matter if it's left or right aligned, both don't have margin-top and sit directly under the header. 

![wri-image-padding.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/9385f3b6-0bc1-4fb4-9d93-53ce543521c4)

**Comment by komejo** [comment]
Fixed and on test: https://test-wri-bene.pantheonsite.io/partner-us/meet-our-partners

**Comment by mshaver** [comment]
Looks great @komejo! Moving this so it can be deployed.

**Comment by komejo** [comment]
Live, looks good: https://live-wri-bene.pantheonsite.io/partner-us/meet-our-partners
