### ISSUE TITLE
Media: Add "Original" image option for inline WYSIWYG images

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#179]
## Overview
Currently when embedding an inline image in a text area from the WYSIWYG editor, the only options for the image are `Embedded` and `Embedded Half`. It would be nice to include in these options the original image size. 

This would allow the user to upload a specific size image and place on the page. The user will have to determine if that image is larger than the viewable area, but with the other options also available they can determine this. 

![bene-image.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/10ae6c6c-b7bb-4c13-b8ae-8787065a125b)

## Dev Tasks
- [x] Add "Original Image" view mode
- [x] Add "Original Image" display mode for image media item
- [x] Select "Original Image" on Media Browser Embed Buttons

**Comment by mshaver** [comment]
Hey @tauno, do you know if this is possible with our current media implementation? I know we have this available for Tolerance and it's nice to have the third options to not use a built in image style if you know the exact dimensions you want to use. This is specifically need for WRI and so if it's just a small configuration change, I'd like to put that in place with their site.

**Comment by mshaver** [comment]
This was added to https://live-wri-bene.pantheonsite.io/. It would be great to capture this code and apply to Bene distro.

**Comment by olivierbouwman** [comment]
@mshaver Did you move this to code review on purpose? Not seeing a linked PR.

**Comment by mshaver** [comment]
@5adiyah can you point @olivierbouwman to where this code is now?

**Comment by 5adiyah** [comment]
https://github.com/thinkshout/bene/pull/374

**Comment by mshaver** [comment]
@mortenson, can you review this work from @5adiyah ?

**Comment by mortenson** [comment]
@mshaver I'll need to write an update hook for this too, I'll try to do that today.

**Comment by mshaver** [comment]
Hi @mortenson was this update hook created? I'm also happy to just create this on the few live sites vs having to do the update hook. The manual process takes maybe 15-20 mins for everything.

**Comment by mortenson** [comment]
@mshaver Yes, that update hook was added: https://github.com/thinkshout/bene_media/pull/18/files#diff-296a30347fa0918b7e0559206d6b9627R283

**Comment by mshaver** [comment]
Perfect @mortenson, closing this issue unless this still needs to be incorporated into a new Bene release?
