### ISSUE TITLE
WRI: Remove `text-align: center` from tiles text area

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#182]
## Overview
The WRI site currently has the entire contents of the tiles paragraph type defined with the `text-align: center`. This makes the title, text and link within that area all center aligned. 

WRI would rather that the text element not have an alignment and instead be set in the WYSIWYG editor for that particular tile. So one tile might have it's text left aligned and one centered. This would likely be done consistently, but you can start to see how the client would like this flexibility. 

**Current Setup**
<img width="1207" alt="results_2_0___willamette_river_initiative" src="https://user-images.githubusercontent.com/179803/36183376-d99e3bd8-10e2-11e8-80a6-e445751453c5.png">

**Flexible Setup**
<img width="401" alt="1results_2_0___willamette_river_initiative" src="https://user-images.githubusercontent.com/179803/36183394-ebb00018-10e2-11e8-8dfe-9851e0a95cd6.png">

Pantheon code:
```
git clone ssh://codeserver.dev.a277c14a-0697-451b-b41a-0631ac4da274@codeserver.dev.a277c14a-0697-451b-b41a-0631ac4da274.drush.in:2222/~/repository.git wri-bene
```

## Theme [hrs]
- [x] Remove align center from tile text area

## This ticket is done when:
- [x] Text aligns left by default, but user can change alignment of tile text area from WYSIWYG.

**Comment by komejo** [comment]
Done and on live.

**Comment by mshaver** [comment]
This has been completed for https://live-wri-bene.pantheonsite.io/, but this should probably be applied to Bene in general. Will open a new issue for this.
