### ISSUE TITLE
Robo Install fails

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/bene#185]
## Overview

Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException:[error]
Circular reference detected for service
"features.config_save_subscriber", path:
"features.config_save_subscriber -> features_assigner". in
/Users/gregboggs/Sites/bene/web/core/lib/Drupal/Component/DependencyInjection/Container.php:141

**Comment by Greg-Boggs** [comment]
Might be an answer here:

https://www.drupal.org/project/features/issues/2948432

**Comment by Greg-Boggs** [comment]
Upgrading to the latest features fixes this.

**Comment by Greg-Boggs** [comment]
After upgrading features and switching to the 8x branch of bene instead of master the next error on install is:

Drupal\Component\Plugin\Exception\PluginNotFoundException: The       [error]
"entity_browser_widget_context" plugin does not exist.

**Comment by jshinrock** [comment]
https://github.com/thinkshout/bene-project/pull/5 solves this issue (if installing from Bene-Project repo).

**Comment by unclegcb** [comment]
True, but with the bene-project updates I get this error instead:

```
Fatal error: Declaration of Drupal\Core\TypedData\ComputedItemListTrait::getValue() must be compatible with Drupal\Core\Field\FieldItemList::getValue($include_computed = false) in /Users/gcb/Sites/bene/web/core/modules/path/src/Plugin/Field/FieldType/PathFieldItemList.php on line 13
```

**Comment by unclegcb** [comment]
@komejo can you have a look and see if anything jumps out at you?

**Comment by komejo** [comment]
Updated installer already installs Drupal correctly, no need to re-run robo install. Updated README.

**Comment by unclegcb** [comment]
Ah, my error above is because I was using php 7.2. There are patches in the works for core, so we should probably not see this issue by the time we move Bene to 7.2.
