### ISSUE TITLE
CORI: move tile background color

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#187]
## Overview
The background color on titles for CORI are being applied to `.paragraph--type--tiles .field--name-field-tiles > .field__item .tile-text`, but instead needs to be applied to `.paragraph--type--tiles .field--name-field-tiles > .field__item`. This will make it so the tiles are equal heights. 

Pantheon code:
```
git clone ssh://codeserver.dev.fcf2c912-81cc-42a1-8bc9-fe80f04cb455@codeserver.dev.fcf2c912-81cc-42a1-8bc9-fe80f04cb455.drush.in:2222/~/repository.git cori
```

## Theme [hrs]
- [x] move `background: #F3F3F3` to next level up 

## This ticket is done when:
- [x] Tiles appear equal heights based on background color

**Comment by komejo** [comment]
Done and on live.
