### ISSUE TITLE
CORI: WYSIWYG button

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#188]
## Overview
The CORI WYSIWYG button styling was never applied and needs to be added to the child theme. The current button style should follow this style:

`.block-bene-home-page-feature-block .field--name-bene-link a`

![cori-button-style.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/f4785b90-c058-4cc4-9f55-b5a7725fbaa9)

<img width="1215" alt="cori-wysiwyg-button" src="https://user-images.githubusercontent.com/179803/37603375-a54f2b7a-2b4b-11e8-9d3a-b0dd234302a5.png">

## Theme [hrs]
- [x] Theme `.button` style the same as above a link

## This ticket is done when:
- [x] WYSIWYG button looks same as a link style in feature paragraphs.

**Comment by komejo** [comment]
Done and on live.

**Comment by mshaver** [comment]
This looks great and is live!
