### ISSUE TITLE
Bene: Tile image width being set

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#191]
## Overview
The tile paragraph type has the image width being set, which causes some issues when tiles are resized at smaller display sizes. This has been fixed in WRI and CORI, but is still an issue with Bene base and FRGK. 

![bene-tile-issue.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/d05b3004-2a9a-4038-bbb0-aaadd7679ef0)

## Theme [hrs]
- [ ] Remove width from image definition on tile theming. 

## This ticket is done when:
- [ ] Tiles look good at all responsive sizes.

**Comment by mshaver** [comment]
Hi @komejo, can you provide the details of how you fixed this for CORI and WRI?

**Comment by jshinrock** [comment]
PR submitted to Bene base. Will update when we have merge.
