### ISSUE TITLE
WRI: Theme MailChimp signup block

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#201]
## Overview
This task will be to theme the mailchimp signup block. This is a configurable block in https://live-wri-bene.pantheonsite.io/admin/structure/block/manage/benenewslettersignup

**Comment by mshaver** [comment]
@komejo, this theming task is waiting for final code from #186. Once that is done we'll have to adjust for WRI child theme.

**Comment by sarahvleigh** [comment]
@komejo @mshaver I have a few recs. The inline labels are my preference but I do know they have some accessibility implications so I'd like to consider this. The gray in this option (hex #707070) is the lightest we can get while still passing color contrast guidelines. The inline options seem to be OK in shorter forms like these (they are an accessibility no-go in longer ones)

The top-labeled option requires a little additional padding between the form fields and the Call to Action text. If we go this route I would also suggest making the CTA text bolder for some contrast with the label text. I'm not loving the red asterisk on blue, but it may just have to stay like that. Open to further investigation--I understand this may have larger Bene implications!


![wri-bene-email-form-design-suggestiona](https://user-images.githubusercontent.com/31553337/39326446-d90f55f4-4949-11e8-93ba-525ba3fdebc7.jpg)
![wri-bene-email-form-design-suggestionb](https://user-images.githubusercontent.com/31553337/39326447-d92974f2-4949-11e8-93cf-03a52a80b1f7.jpg)

**Comment by komejo** [comment]
Done and on live, also themed for mobile and fixed logged-out subnav.
