### ISSUE TITLE
Bene: Tile height issues

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#202]
## Overview
The height of tiles is set to the largest tile text and all tiles inherit that value. This is likely the way equal height tiles work, but it does have some issues. 

* One larger tile sets the pattern for all as seen here: https://live-wri-bene.pantheonsite.io/results
* Some elements of the tile do not get calculated in the height as seen in this screenshot:
![Results_3_0___Willamette_River_Initiative.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/c01ad817-cbd2-4d06-bbea-cc6fee74bbd0)

I'm not entirely sure the best path forward here. Just recording for discussion. 

## This ticket is done when:
- [ ]
- [ ]

**Comment by jshinrock** [comment]
@mshaver can you confirm this is still an issue? I am not able to replicate with link provided.

**Comment by mshaver** [comment]
@jshinrock, this is looking great on https://dev-wri-bene.pantheonsite.io/results. @tauno will be pushing some other work up so I'll wait to deploy at that point.
