### ISSUE TITLE
Clean up failing patches

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/bene#205]
## Overview
Composer install currently throwing errors on ~3 patches. Review to see if they need to be updated or removed from composer, and proceed from there.

This is a quick pass: if any look especially challenging, simply create separate tickets for them and move on. We just want to clean up anything easy before rolling 1.0.3.

**Comment by jshinrock** [comment]
patches throwing errors on drupal/core v8.4.6

2880445 - Config sync should not throw a warning when not being writable

**committed to 8.x-dev (now merged, see screenshot or discussion link)**

![screen shot 2018-04-16 at 3 02 53 pm](https://user-images.githubusercontent.com/662848/38832169-5c753ef6-4187-11e8-9980-22f8b28e3be3.png)

patches throwing errors for migrate_tools

Migrate Tools dashboard plugin manager/config deriver UI issues - https://www.drupal.org/node/2825846#comment-12080570

**committed to 8.x-4.x (see screenshot or discussion link)**

![screen shot 2018-04-16 at 3 01 55 pm](https://user-images.githubusercontent.com/662848/38832170-5c87dc8c-4187-11e8-9128-89dba37311fa.png)
