### ISSUE TITLE
Bene: Embedded half image captions with longer text extend image width rather than wrap

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#210]
## Overview
The Embedded Half image style for inline images allows captions, but if the caption text extends beyond the half image width style, the image begins to increase in size. What we need is for the text to wrap on the half image. 

You can see this happening on this page:
https://live-wri-bene.pantheonsite.io/test-page

## This ticket is done when:
- [x] Inline images with the Embedded Half image style and the caption longer than the half style should wrap the text.

**Comment by komejo** [comment]
Fixed by adding some JS to the WRI child theme which adds the class 'embedded-half' to the parent `figure`. This should be replaced in core distro with a function to add it on the backend, at which point the JS can be removed.
