### ISSUE TITLE
Bene: horizontal scroll issue on internal pages

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#229]
## Overview
#190 solved the horizontal scroll issue on the home page, but didn't solve for internal pages. This ticket is to solve the same problem across Bene pages. 

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mortenson** [comment]
@mshaver Is this happening on any sites using the bene_parent base theme? I made a fix to bene_base in #364 that resolves this for sites like WRI that use bene_base.

**Comment by mshaver** [comment]
@mortenson, it does appear to be happening on new sites as well. See here: https://friends.org/about-us/our-story

![friends-scroll-issue](https://user-images.githubusercontent.com/179803/58997392-4c440c80-87b1-11e9-8a4c-695a9f06fbe3.png)

**Comment by mortenson** [comment]
@mshaver Thanks - the class was different between themes so I missed that. PR should fix this, I'll merge it soon.

**Comment by aprice42** [comment]
Fix is ready for review in the above PR.

**Comment by mshaver** [comment]
Hi @aprice42, looks like you fixed this for friends, but there is likely something with STTR that is still causing it in the child theme. You can see on both the home page and internal pages of https://8211-test-streettrust-bene.pantheonsite.io/ that it's still got a horizontal scroll. Is this something you can look at or we can have @cpolk15 jump into?
