### ISSUE TITLE
Parent Theme: Rename STTR Bene Parent Theme

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#240]
## Overview
With the change in theming structure finalized, we need to change the current STTR parent theme to make room for the official `bene_parent` name we want for the new version.

**Comment by mshaver** [comment]
Adding @rjacobsen0 to this since it looks like she took a stab at this.

**Comment by unclegcb** [comment]
Yep, work is in the `bene-parent-with-extends` branch.
