### ISSUE TITLE
Update Responsive Image Style Configuration

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/bene#242]
## Overview
The Responsive Image style configurations are all tied to themes (for breakpoints), meaning most are tied to the bene_base theme. As that theme will be retired, we need to reconfigure them to use bene_parent.

This implies both changing the config files, and putting a hook update in place for existing sites. Or perhaps a hook_install on bene_parent.

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mshaver** [comment]
@mortenson assigning this to you as I'm not sure if we should close or actually estimate?

**Comment by mortenson** [comment]
@mshaver This has already been done, looks like:
```
❯ find . -name '*responsive_image.styles.*' | xargs grep breakpoint_group
./modules/bene_hero_block/config/install/responsive_image.styles.background_hero.yml:breakpoint_group: bene_parent
./modules/bene_page/config/install/responsive_image.styles.header.yml:breakpoint_group: bene_parent
./modules/bene_page/config/install/responsive_image.styles.embed.yml:breakpoint_group: bene_parent
./modules/bene_page/config/install/responsive_image.styles.full_width_feature.yml:breakpoint_group: bene_parent
./modules/bene_page/config/install/responsive_image.styles.embed_half.yml:breakpoint_group: bene_parent
./modules/bene_page/config/install/responsive_image.styles.tile.yml:breakpoint_group: bene_parent
```
Closing out now.
