### ISSUE TITLE
Bene Jefe: Review Action Plan

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#245]
## Overview
Sadiyah's ticket spec doc for Bene Jefe: https://docs.google.com/document/d/1DmhO_VDyYls-l5FCbPy5qp17zh1J-3-nxr2SZNQY0E4/edit

Please review, add comments, notes etc. 

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by unclegcb** [comment]
The implementation section, perhaps the one @5adiyah is most comfortable with, is pretty thinly described, which usually makes the estimate less precise. I'd love a few more steps: Create the new theme, set initial variables, make customizations, etc.
