### ISSUE TITLE
Media Video: paragraph selectors changed with media update

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#250]
## Overview
The update of core and media left a selector for the media paragraph off. If you add a media paragraph and include a video in that, the video appears full screen. The video should be contained and it appears the following selector controlled that prior to the update: 

`.page-node-type-page .paragraph--type--media .media-video`

It appears the new selector should be:

`.page-node-type-page .paragraph--type--media media--type-video`

![bene-media-bug-video](https://user-images.githubusercontent.com/179803/48365251-42b15680-e65f-11e8-9c46-408a85cc4579.png)

## Dev [hrs]
- [ ] Fix media paragraph video width

## This ticket is done when:
- [ ] Adding a media paragraph with a video results in the video not being full width.

**Comment by unclegcb** [comment]
Good catch and correct indeed. I've got those changes up on https://20test-cori.pantheonsite.io/julias-test-page and ready to get into a release from a bene branch called "video_fixes".

**Comment by mshaver** [comment]
Looks good @unclegcb! Should be ready for updating the release and we can get these sites updated. I'd like to reach out to each client on a window to update, so let's hold off on the actual update till we schedule it.
