### ISSUE TITLE
Security Update Jan 16 2019

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/bene#276]
## Overview
Drupal 8.5.10
Pull in latest theming updates for OTFO.

**Comment by unclegcb** [comment]
Bene 2.06 RC2 available on OTFO:
https://rc206-otfo-bene.pantheonsite.io/

**Comment by unclegcb** [comment]
Bene 2.06 RC2 available on CORI for testing:
https://rc206-cori.pantheonsite.io/

**Comment by unclegcb** [comment]
Bene 2.06 RC2 available on Streettrust for testing:
https://rc206-streettrust-bene.pantheonsite.io/

**Comment by juliaford** [comment]
assuming we just need to tell FRGK to do the update? @unclegcb @mshaver

**Comment by juliaford** [comment]
and all looks good @unclegcb except that it still says there is a security update on the multidev? That is weird right?

**Comment by unclegcb** [comment]
@juliaford it looks like there's a paragraphs security update out there, too. I'll get it into the next release, but it shouldn't effect Bene sites as it is only a problem in concert with other modules and configuration.

These updates are pushed for client review:

https://test-cori.pantheonsite.io/
https://test-wri-bene.pantheonsite.io/

OTFO will get rolled in before next QA work. Streettrust is live.

Yes, we need to tell FRGK there's an update available, and also probably ok to tell them that we don't think there are any attack vectors in Bene for the security issue, so they shouldn't panic.

**Comment by mshaver** [comment]
I'm unable to reproduce the issue with theming I was experiencing and it appears https://test-cori.pantheonsite.io/news is also looking fine. @unclegcb, I'll reach out to WRI and CORI saying we'll be pushing the updates.

**Comment by unclegcb** [comment]
@mshaver I deployed for WRI and CORI last week, but FRGK still has not applied this update.

**Comment by mshaver** [comment]
I've reached out to FRGK and so closing this issue.
