### ISSUE TITLE
Automate building of sites from minimal repos

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/bene#278]
## Overview
Currently we are committing entire Pantheon repos: that's really messy, and makes it hard to work on Bene at the same time you are working on a site (which is a natural process)

## Brainstorm notes from Gabe
ideal Bene repo:

Composer based? Seems insufficient since we need to use the Pantheon repo itself.
Able to apply patches to Bene? Probably just incompatible with upstream model
Directory & script, then. Like D7 projects, composer used only to maintain scripts.
Contents:
— .circleci/
— .gitignore (significant. Only looks at the files specified here.)
— composer.json
— composer.lock
— modules/custom/
— themes/
Deploy Script does the following:
Clone pantheon repo
Copy themes and module directories into /web/themes and /web/modules/custom
Generate commit message
Push to matching branch on Pantheon
Build script does the following:
Clone Pantheon repo (if specified — Otherwise clone Pantheon upstream)
Deletes .git
Copies repo itself into /web of new build

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mortenson** [comment]
I added some thoughts for this in #280

**Comment by mshaver** [comment]
It sounds like #280 is where this all happened and we could possibly close this issue? Is that correct @mortenson or @unclegcb

**Comment by mortenson** [comment]
@mshaver The deploy process part of this work is basically done, yes.
