### ISSUE TITLE
Bene: Mobile Nav accessibility causing text to show within mobile nav

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#279]
## Overview
When some of the accessibility features were added to Bene, it caused a regression in the mobile nav. You can currently see the "Mobile Menu" text showing up within the hamburger menu.

## Sites
https://www.willametteinitiative.org/
https://www.columbiariverkeeper.org/

## Screenshots
![bene-mobile-nav.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/003a7c80-09a5-42af-970e-6589870b4b1c)![bene-mobile-nav2.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/cea3fc79-5e96-4b25-8655-601827ee4207)

## This ticket is done when:
- [ ] Mobile menu does not show "Mobile Menu", but text is available for screen readers.

**Comment by juliaford** [comment]
@mortenson to you, hot fix of sorts!

**Comment by mortenson** [comment]
PR in review.

**Comment by mshaver** [comment]
@unclegcb was this included in a recent release of Bene?

**Comment by unclegcb** [comment]
It appears to be, but it's still an issue on the latest release: http://test-cori.pantheonsite.io/

Might be a regression, or that the child themes need this code as well on Cori and WRI. @mortenson I'm guessing the latter?

**Comment by mortenson** [comment]
@unclegcb I'd guess that too. The code I changed is still untouched in HEAD.

**Comment by unclegcb** [comment]
Hm. That sass file doesn't exist on either site's sub-theme.

**Comment by mortenson** [comment]
@unclegcb It's part of the styling inherited by the base theme, right?

**Comment by unclegcb** [comment]
I would expect it to be, but the issue still exists using the fixed base theme.
