### ISSUE TITLE
Media: Improve document embedding on WYSIWYG editor

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#289]
## Overview
The current media browser allows a person to add a document (PDF) to the site or to place a document already added via the media browser or via /media/add. The problem comes when trying to embed the document on the page. If you select an existing document from the library it will embed that document and link to the file. But if you try embedding the document you try to upload in this one action, it does not allow this. 

## Steps to reproduce
1. Create page content type
2. Add Rich Text paragraph
3. Select Media button
4. Upload PDF document and try to "place" document
5. It is not possible to place the document

## This ticket is done when:
- [x] A fix similar to https://www.drupal.org/project/lightning_media/issues/2965767 is implemented, OR
- [ ] Figure out how Lightning Media is supporting this now and update our code to align with theirs (they're not using `hook_media_source_info_alter` anymore, from what I can tell)
- [x] Documents can be uploaded without errors

**Comment by olivierbouwman** [comment]
https://github.com/thinkshout/bene_media/pull/16
Decided not to spend time investigating how lightning media does things now. Hopefully we can just switch to D8 core media at some point anyway.

**Comment by mshaver** [comment]
@mortenson, was this work already incorporated into a Bene release through the update of Bene Media? Just trying to assess where this issue is at.

**Comment by mortenson** [comment]
@mshaver Yes, you should be able to embed documents in WYSIWYG.

**Comment by mshaver** [comment]
Excellant!
