### ISSUE TITLE
Media: better display of documents in Media Browser

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#301]
## Overview
The media browser has documents that are listed and can be embedded into a page. The default view of the documents in the media browser is not helpful as there are no document names or other meta data related to the document. 

## Screenshot
![bene-media-browser-docs.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/07d189fd-8f22-4e5d-8282-a9407e629e23)

## Dev [hrs]
- [ ] Improve display of documents in the media browser

## This ticket is done when:
- [ ] The media view mode is updated to show the filename
- [ ] Custom CSS is added to properly style the filename

**Comment by 5adiyah** [comment]
https://github.com/thinkshout/bene_media/pull/15

**Comment by mshaver** [comment]
@mortenson, can you assess where this issue is at as well within Bene Media?

**Comment by mortenson** [comment]
@mshaver This change should have been rolled out to all bene sites.
