### ISSUE TITLE
Media: image preview is not showing even after it's been selected

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#356]
@juliaford commented on [Tue Apr 30 2019](https://github.com/thinkshout/otfo-bene/issues/104)

see:
![Screen Shot 2019-04-30 at 4.23.57 PM.png](https://images.zenhubusercontent.com/58ffba9c51aa2c30577c724f/dec76dfc-142d-412a-bfe7-566c276c376f)

---

@olivierbouwman commented on [Thu May 02 2019](https://github.com/thinkshout/otfo-bene/issues/104#issuecomment-488736475)

Dev instructions (so we can replicate on Bene distro).
- [x] Create new view mode for media at /admin/structure/display-modes/view/add/media, name it "Form preview" (or something better?).
- [x] On /admin/structure/media/manage/image/display under "Custom display settings", enable "Form preview".
- [x] On /admin/structure/media/manage/image/display/form_preview, set Name and Image (thumbnail).
- [x] On /admin/structure/types/manage/page/form-display (and any other places where we have this issue) set "Entity display plugin" to "Rendered entity" and "View mode" to "Form preview"
- [x] Repeat for all media types and export config to Bene distro
- [x] Copy the page form display changes into bene/config/install
- [x] Copy all media config changes including form_display into bene_media/config/install
- [x] Make a branch of bene and bene_media, push both branches, and open PRs here and at https://github.com/thinkshout/bene_media

**Comment by mortenson** [comment]
@mshaver I think this is already spec'd.

**Comment by mshaver** [comment]
@mortenson, yes I realized that after making those changes! :) I think it's ready to be worked on or assigned to another person. I went ahead and assigned to you not know if you'd have extra time this week to take it on.

**Comment by mshaver** [comment]
@mortenson, I believe this was solved with the latest 2.8.11 release right?

**Comment by mortenson** [comment]
@mshaver Yes, this should be solved.
