### ISSUE TITLE
Audit existing Bene sites for config modifications

### ISSUE THREAD

**Issue by mortenson** [thinkshout/bene#357]
## Dev [5 hrs]
- [x] Export config for every bene site onto your local machine
- [x] Install a fresh Bene site and export its config
- [x] Run a diff tool between the directories and see what is commonly modified. Some config like the site name is not significant, use your discretion.

## This ticket is done when:
- [ ] An audit report is created summarizing what config is commonly modified in Bene sites

**Comment by mortenson** [comment]
Bene config modification report

CORI
=====
- Media tags not present in form displays
- url_redirects field added to node form displays
- **Data model change**: Media image type uses "image" field, not "field_media_image"
- Most media view displays altered
- field_media_video_embed_field shown in video embedded view mode
- Many additional modules installed
- Using bene_base theme instead of bene_parent
- "Byline" style added to basic_html format
- Buttons changed in full_html format
- Basic/full html has different allowed tags
- focal_point not used for many image styles
- Media images not revisionable
- Metatags altered, do not include canonical_url
- Media action config appears to use old plugin
- Front-page view altered to change empty message
- Media admin view seems out of date

Streettrust
========
- expand_all_items: false added to a few menus
- **Data model change**: Media image type uses "image" field, not "field_media_image"
- media_tags not used for image media_browser form display, focal_point used
- url_redirects field added to node form displays
- field_media_video_embed_field shown in video embedded view mode
- Event search_result display modified
- Menu link override added for contact__site_page
- "Orange Button" style added to text formats
- Basic/full html has different allowed tags
- embed_half/embed_l image style has different image width
- Meta tags for user differs
- R4032login settings differ
- Media action config appears to use old plugin
- user.mail settings differ
- Front-page view altered to change empty message
- Media admin view seems out of date

WRI
====
- expand_all_items: false added to a few menus
- **Data model change**: Media image type uses "image" field, not "field_media_image"
- focal_point used for image media_browser form display
- url_redirects field added to node form displays
- Media tags not present in form displays
- Many additional modules installed
- Menu link override added for contact__site_page
- basic/full html has different allowed tags, styles changed
- homepage_hero_xl/homepage_hero_l image style has different width
- Global metatags differ
- Meta tags for user differs
- Media action config appears to use old plugin
- user.mail settings differ
- Authenticated role permissions differ
- Front-page view altered to change empty message
- Media admin view seems out of date

OTFO
=====
- expand_all_items: false added to a few menus
- Media tags added to audio form display
- Media tags added to video form display
- url_redirects field added to node form displays
- field_media_video_embed_field shown in video embedded/embedded_half view modes
- Many additional modules installed
- Menu link override added for contact__site_page
- No styles allowed in full_html text format
- Buttons removed from restricted_html text format
- plain_text allowed for rich_text paragraph type
- basic/full html has different allowed tags, styles changed
- Meta tags for user differs
- Revisions enabled for pages
- R4032login settings differ
- user.mail settings differ
- Authenticated role permissions differ
- Media view missing bulk form

Summary
=======

- Older sites have a different source field for the "Image" media type. This will make future updates difficult as the field name will be different in Views displays, form/view displays, etc.
- Most administrative views have been modified with the addition or removal of a filter
- Most text formats and filters have been modified
- Metatag settings seem out of date
- Role permission changes are rare but do (and must) happen when a non-standard module is used
- The addition of the Bene Redirect feature, or any extra module will result in form/view displays being modified

**Comment by juliaford** [comment]
Estimating getting everyone up to date in 13 hours.

Specific tasks/thoughts:

Migrate media image type source field from “image” to “field_media_image” - 3 hours to write update hook

Media tags not present in form displays - 1 hour to write update hook

CORI: Altered many media displays - would need to investigate to find out why

field_media_video_embed_field shown in video embedded view mode - 30 minutes to investigate if worth adding to main profile, if so 1 hour to write update hook

We can’t fix sites that altered text formats (changed buttons/styles) or filters (changed allowed tags). Writing update hooks is still possible to add or modify a button’s configuration so maybe no work to do here.

CORI: focal_point not used for many image styles - Change manually. (10 minutes)

CORI: Media images not revisionable - Change manually. (10 minutes)

CORI/WRI: Metatags altered - Change manually to add canonical URL and review other differences (20 minutes)

Media action config appears to use old plugin: Need to look at Streetrust/WRI/CORI to see if this affects functionality, if so let’s write an update hook. 1 hour.

Media admin view seems out of date - 1 hour to write update hook.

“expand_all_items: false” added to a few menus - 30 minutes to investigate if worth adding to main profile, if so 1 hour to write update hook

focal_point used for image media_browser form display - 1 hour to write update hook

Menu link override added for contact__site_page - 30 minutes to investigate if worth adding to main profile, if so 1 hour to write update hook

Revisions enabled for pages - Already existing issue but we should knock that out soon, 1 hour.

Note:

Image style widths seem commonly changed, so if we write update hooks for those in the future, we’ll need to check that the existing value is the default value.

**Comment by mshaver** [comment]
@mortenson, isn't most of this issue complete at that point? Let's figure out how to get this pushed to the various sites in the next few weeks.

**Comment by mortenson** [comment]
@mshaver All of the code for this task is still in code review, I think. Ref:
https://github.com/thinkshout/bene_media/pull/8
https://github.com/thinkshout/bene/pull/360
