### ISSUE TITLE
Tile Paragraph: make theming generic so parts can be used more flexibly  

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#365]
## Overview
The tiles paragraph type was always intended to be a flexible content piece that Bene sites could use in various ways. Clients may want to fill in all the fields or just a subset of them. This could provide a very flexible system for Bene sites, where you might only fill in the image field and link and have a grid of images. Or you could fill in just the text field and have a column style layout. The goal is really to make tiles as flexible as our users need them to be. 

With that in mind, we need to make more of the theming of tiles be less prescriptive if elements are not filled in. 

Current Fields:
* Image
* Lead
* Title
* Text
* Link
   * URL
   * Text

## Example page
https://test-otfo-bene.pantheonsite.io/flexible-tile-example-page

## Screenshot
![otfo-tile-theming-issue](https://user-images.githubusercontent.com/179803/65193289-6ab3d800-da2f-11e9-8207-a6fa7f47b77c.png)

## Theme
- [ ] Ensure that tile paragraphs have appropriate styling for every combination of optional fields. For example - only image, only lead, only title, only text, only link, only image+lead, etc. 
- [ ] Ensure spacing above and below tiles is good, including against other paragraphs. 

Note that the estimate for this may need to be adjusted if each combination becomes cumbersome to account for. I'm hoping that having a good placeholder for the image and having generic styling for the other fields means that this will be a straightforward task.

## This ticket is done when:
- [ ] Tile paragraphs look good regardless of what fields are filled in.

**Comment by mshaver** [comment]
@mortenson has determine this is largely working this way and it's just at the child theming level where it's not working so well. This was evident on https://friends.org/ when trying various combinations. We probably need to do 2 things for this issue:
1. Make any Parent them changes so style changes at child level have independent elements. 
2. Adjust OTFO so their tiles work for this scenario

**Comment by mshaver** [comment]
@mortenson OTFO specific.

**Comment by mshaver** [comment]
@mortenson, screenshot and link to sample page with tile combos. The example uses only 3 tiles at a time, but we will need to account for times when they put more than 3 in place.

**Comment by mortenson** [comment]
@mshaver How does this look? https://365-tile-otfo-bene.pantheonsite.io/flexible-tile-example-page

**Comment by mshaver** [comment]
This is great @mortenson! This really solves the issue and provides the flexibility they need to use the tiles in various ways. I'm going to move this to ready for deploy and we can schedule some time to get this on the live site.
