### ISSUE TITLE
Responsive Tables

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#366]
## Overview
The current WYSIWYG ckeditor has the table button and Bene sites can add tables pretty easily to most of the content areas. Right now these tables are not responsive out of the box. This issue is to add the https://www.drupal.org/project/responsive_tables_filter module so any table added in the body is automatically responsive. 

## Dev [6 hrs]

- [x] Add the responsive_tables_filter to the bene profile's composer.json file and enable it by default
- [x] Ensure that the `<table> <th> <tr> <td> <thead> <tbody> <tfoot>` tags are allowed in all text formats that allow tables.
- [x] Decide what the default Tablesaw behavior should be for tables. See the "Select which default table behavior you prefer" note at https://www.drupal.org/project/responsive_tables_filter for details.
- [x] Write an update hook to enable responsive_tables_filter on existing sites and possible re-configure text formats to allow for the right tags/classes.

## Theme [1 hrs]

- [x] Make sure that tables look good on mobile devices.

## This ticket is done when:
- [x] All tables in WYSIWYG are responsive.

**Comment by mortenson** [comment]
@mshaver What's the best way for you to QA this change? Want me to spin up a multidev of a client site or find the Bene QA site we set up (can't remember the path)? I can also record a video or do a call.
