### ISSUE TITLE
Bene 8.2.11 QA

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#375]
## Bene 8.2.11 RC
https://8211-test-streettrust-bene.pantheonsite.io
https://www.thestreettrust.org/

https://8211-test-otfo-bene.pantheonsite.io
https://friends.org/

## GENERAL
- [x] horizontal scroll issue exists on home page and interior pages: #229

## STTR
- [x] Hero header should be uppercase
- [x] Tiles header should be uppercase
- [x] Tile link style should be STTR button style
- [x] Tile text link style should have correct color and hover
- [x] Rich text size is too small overall
- [x] Rich text link colors need to be set
- [x] Rich text header styles need to be uppercase
- [x] Rich text images are not showing up [example](https://8211-test-streettrust-bene.pantheonsite.io/initiatives/women-bike)
- [x] Event text color not correct
- [x] Listing page filters not showing calendar icon on date filters (Parent)
- [x] News & Event date alignment needs to be contained within max width (Parent)
- [x] `button-wrapper` padding is causing issues with tile buttons. Not sure if this is necessary with parent theme or should be removed in only child for STTR. It looks like it was removed on OTFO:
![bene-button-wrapper](https://user-images.githubusercontent.com/179803/62481143-73de3380-b766-11e9-82a5-919920f50a90.png)
- [x] Add hover color to sub-menu items:
![bene-sub-menu-hover](https://user-images.githubusercontent.com/179803/62481361-18607580-b767-11e9-8a1f-18bbf7811318.png)
- [x] Add active state to utility menu
![bene-utility-menu-active-state](https://user-images.githubusercontent.com/179803/62481516-79884900-b767-11e9-8a59-8e256822bc75.png)
- [x] Match font sizes between Tiles and Rich Text paragraphs so font size is the same for normal text. 
![sttr-font-sizes](https://user-images.githubusercontent.com/179803/62497186-0e06a180-b790-11e9-9cfe-ec645164d2c1.png)
- [x] News & Event content type listing pages and detail pages should match Page styles for Intro, body text and headers. 
![sttr-news-listing page](https://user-images.githubusercontent.com/179803/62497190-1068fb80-b790-11e9-8d07-f907a136128d.png)

## OTFO Mobile
- [x] Mobile menu being covered up by sub-page hero image
![otfo-mobile-menu](https://user-images.githubusercontent.com/179803/62553422-27592d80-b824-11e9-873f-0385c625a805.png)
- [x] Mobile menu needs "X" close when open
- [x] Increase mobile padding in parent
![otfo-mobile-padding](https://user-images.githubusercontent.com/179803/62553910-0c3aed80-b825-11e9-9bf2-9afc692ffe01.png)

### STTR: to make better in parent
- [x] Listing page items text size for titles and text
- [x] Text size on News and Event detail pages need to align with rich text paragraph values

## OTFO
- [x] Hero button style
- [x] Hero color fade
- [x] Nav "Donate" styling
- [x] Feature paragraph title color/size (not showing up at all right now)
- [x] Feature paragraph text alignment
- [x] Footer background color
- [x] Footer social links bg color
- [x] Sub page hero color overlay
- [x] Rich text pull quote style needs to be set
- [x] Rich text link/hover style
- [x] News & Event max width of page not set (Parent)
- [x] News & Event date alignment needs to be contained within max width (Parent)
- [x] Full width paragraphs on News & Events [example](https://8211-test-otfo-bene.pantheonsite.io/news/2019/7/2019-legislative-recap)
- [x] Nav hover line being cut off by hero image:
![otfo-nav-hover](https://user-images.githubusercontent.com/179803/62483945-d25ae000-b76d-11e9-8f0f-4ce35ade2f02.png)
- [x] Intro line padding below on home page (not sure if we can just do this in the WYSIWYG, as interior pages seem fine? 
![intro-line-padding](https://user-images.githubusercontent.com/179803/62484109-49907400-b76e-11e9-8446-c767d9418fe2.png)
- [x] Rich text blockquote text should be larger size (approximately 20px)
- [x] Rich text links should have underline
![otfo-rich-text-links](https://user-images.githubusercontent.com/179803/62484754-b35d4d80-b76f-11e9-851b-df0ab1c114b4.png)
- [x] Date field on News content type is not contained with max-width of page:
![otfo-date-issue](https://user-images.githubusercontent.com/179803/62496072-a9961300-b78c-11e9-8a3e-20dce12dbdaa.png)
- [x] News link styles should match Page/Rich Text link styles. We will need to carve out exception for `blockquote` since having that underlined will not work. 
![otfo-link-styles](https://user-images.githubusercontent.com/179803/62496155-ec57eb00-b78c-11e9-9bb7-b76943f9b82f.png)
![otfo-blockquote-links](https://user-images.githubusercontent.com/179803/62496235-2aeda580-b78d-11e9-8d7f-4b8c187b4c87.png)
- [x] News feature paragraph is not extending full width on detail pages. https://8211-test-otfo-bene.pantheonsite.io/news/2019/7/2019-legislative-recap: 
![otfo-news-feature-paragraph](https://user-images.githubusercontent.com/179803/62496331-786a1280-b78d-11e9-8887-0dcc96e7ebc3.png)
- [x] Tiles button hover should be set to `--color-secondary-c`, but has background color on hover now. 
![otfo-mobile-images](https://user-images.githubusercontent.com/179803/62640187-dd407c80-b8f5-11e9-84ab-9a9f2751a5bf.png)
- [x] Rich text blockquotes seem to not be getting the right font size or it's being overriden by the `<p>` tag below. 
![otfo-blockquote](https://user-images.githubusercontent.com/179803/62641745-26de9680-b8f9-11e9-8477-5356c7bb236c.png)
- [x] Event detail page needs all text to align to body container like it does on page content type. https://8211-test-otfo-bene.pantheonsite.io/events/2019/2019-mccall-gala
![otfo-event-detail-alignment](https://user-images.githubusercontent.com/179803/62642201-0fec7400-b8fa-11e9-8ab5-413fdd4174d2.png)
- [ ] Alignment of event listing items (https://8211-test-otfo-bene.pantheonsite.io/get-involved/events). 
![otfo-event-listing-alignment](https://user-images.githubusercontent.com/179803/62642343-5346e280-b8fa-11e9-9293-fba9cb335772.png)

**Comment by cpolk15** [comment]
In relation to: Rich text images are not showing up 
My personal dev-copy is showing the images after setting up stage_file_proxy
Example page doesn't even have a img tag in the markup.

**Comment by cpolk15** [comment]
Regarding: Rich text pull quote style needs to be set
Extra padding seems unnecessary due to changed paragraph with for normal text.

**Comment by mshaver** [comment]
- [x] Match font sizes between Tiles and Rich Text paragraphs so font size is the same for normal text. 
![sttr-font-sizes](https://user-images.githubusercontent.com/179803/62497186-0e06a180-b790-11e9-9cfe-ec645164d2c1.png)
- [x] News & Event content type listing pages and detail pages should match Page styles for Intro, body text and headers. 
![sttr-news-listing page](https://user-images.githubusercontent.com/179803/62497190-1068fb80-b790-11e9-8d07-f907a136128d.png)

**Comment by mortenson** [comment]
>Intro line padding below on home page (not sure if we can just do this in the WYSIWYG, as interior pages seem fine?

This should be done in WYSIWYG, the line under the blue text is just an `h4` styling, all of the text there (i.e. "Oregon's 241 towns ...") is part of the intro.

**Comment by mortenson** [comment]
>News feature paragraph is not extending full width on detail pages

@mshaver This is due to new parent theme styles that add a padding to all node content - do you want to do an override for OTFO (maybe a negative margin for the hero?) or keep as-is?

**Comment by mortenson** [comment]
>Mobile images are extending outside content area. This bug exits already, but would be nice to fix in parent if possible

@mshaver Lets move this to a follow up since it wasn't introduced here.

**Comment by mortenson** [comment]
@mshaver Both sites should be ready for another round of QA.

**Comment by mortenson** [comment]
>News & Event content types are not showing the correct link colors

>Listing page Intro field theming needs to match Page Intro field theming

@mshaver This looks the same on the live site - is this related for this work or a new issue? I'd like to save all other feedback for follow ups.

**Comment by mshaver** [comment]
OK, will be creating issue specific to OTFO for. @mortenson 

> News & Event content types are not showing the correct link colors

> Listing page Intro field theming needs to match Page Intro field theming

**Comment by mshaver** [comment]
Moving comment to new issue.
