### ISSUE TITLE
News & Events: detail pages should be using site link styles

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#379]
## Overview
The News & Event content type detail pages need to match more of the same styles as the Page content type and specifically for the link styles on the detail pages. These should be inherited from the Parent in most cases and rarely would be overridden at the child level for these content types. 

- [ ] News & Event content types are not showing the correct link colors. Should match link colors on Page content type. https://8211-test-otfo-bene.pantheonsite.io/latest
<img width="820" alt="otfo-even-news-link-color" src="https://user-images.githubusercontent.com/179803/62643043-e3395c00-b8fb-11e9-8f56-fc034b5ed0e8.png">

**Comment by mshaver** [comment]
@mortenson OTFO specific.

**Comment by mshaver** [comment]
@mortenson, I confirmed with @juliaford that the links should follow the current link style seen on the page content type; black with underline. Here is an underline and page you can find an example. 

https://friends.org/about-us/affiliates

![image](https://user-images.githubusercontent.com/179803/65697646-1fea1f80-e030-11e9-84db-85b48e464efa.png)

**Comment by mortenson** [comment]
@mshaver Per our in-person conversation -  the default link styling on the site is orange without an underline, not black with an underline. The black/underline styling is a bug, even if it's a desirable one. Does the client want all default links to have this style on the site?

**Comment by mshaver** [comment]
Hi @mortenson, I do think the default needs to switch to this style that is bug! :) I would just caution that I believe this is only in the body area between the page, news, events and listing page content types. So links in the header, footer, subnav, non-rich text paragraphs should be left along. I'm hoping that is already accounted for in this bug, but just wanted to let you know again.
