### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#50]
## Overview
Content type and basic listing.

## Design/UX [hrs]
- [x] Design events landing page
Final Designs: https://projects.invisionapp.com/share/ABCHYACFK#/screens/250306211
- [x] Full page event design

## Dev [8 hrs]

- [x] Event content type
  - [x] Description (textarea) (bene_event_description)
  - [x] Location (textarea) (bene_event_location)
  - [x] Date Range (bene_event_date_range)
    - [x] Enable Datetime Range module (datetime_range)
    - [x] Date Type = Date and time

- [x] View
  - [x] Display content of type "event"
  - [x] Display events in reverse chronological order
  - [x] Sort by date?
  - [x] Search by event title?
  - [x] Create "Past Events" view that lists events that have passed already

## Theme [8 hrs]

- [x] Listing pageFollow design although there are no sort options and instead there are filters for keyword and date range
  - [x] Filter form
  - [x] Teasers
  - [x] Pager
- [x] Theme full view of an Event

**Comment by mshaver** [comment]
Hi @tauno, it would be great to spec this feature as well for @ruscoe to tackle next week. That way he'll have a full slate of work next week. If you can do this by Monday 24th, EOD

**Comment by juliaford** [comment]
@tauno @ruscoe  is this ready for Joe?

**Comment by ruscoe** [comment]
@juliaford There's not much to it, but the event list could be themed.

Do we have designs for the event list? Right now it looks like this:

![screen shot 2017-08-15 at 2 58 55 pm](https://user-images.githubusercontent.com/87952/29338484-4ef618f4-81ca-11e7-8ec0-a16310a30e36.png)

**Comment by mshaver** [comment]
@vickibrown, the events listing is only required for CORI right now, but this would be good to put on your list once you have the core CORI design approved. 

It's likely the event list would be reverse chronological with the closest event at the top. After the event has passed, it should drop off the list. At some point we might need to add a "Past Events" view below the "Upcoming Events" so users can get to past events easily as well. cc @tauno and @ruscoe, as I'm not sure the current functionality acts this way?

**Comment by tauno** [comment]
Filtering by date is not included at the moment since Drupal core apparently doesn't support it well. Working on that though.

**Comment by tauno** [comment]
I added a core patch to support filtering by relative dates so it will now just show events ending >= now.

**Comment by komejo** [comment]
Added Migration for paragraphs and events, past events view block, and sample data to spreadsheet. Also added events and past-events pages and placed blocks.

**Comment by komejo** [comment]
Add Listing Page migration, added the appropriate blocks, themed.

**Comment by juliaford** [comment]
![screen shot 2017-09-29 at 3 21 26 pm](https://user-images.githubusercontent.com/28023410/31038220-533ee908-a52a-11e7-9de2-520f126f951f.png)
Events and News search side bar don't match design

**Comment by juliaford** [comment]
Sub nav is still not working here, the bullet point is showing up

**Comment by heypaxton** [comment]
@vickibrown do you have an opinion on how you want the event detail page to look? It's the same as other pages except it has a date and location fields. Which I am inclined to align to the left. But I'd like a vision on the font set to use for the date, org name and address that are at the top of the body.

**Comment by vickibrown** [comment]
@heypaxton No problem, I can quickly lay this out.

**Comment by vickibrown** [comment]
@heypaxton The sketch file is updated with this design. https://invis.io/ABCHYACFK#/256949477_Event_Detail

**Comment by heypaxton** [comment]
@tauno if possible, please remove the break tags from the address field. Here's what we are trying to acheive https://projects.invisionapp.com/share/ABCHYACFK#/screens/256949477_Event_Detail

**Comment by tauno** [comment]
Break tags are removed now with a patch.
