### ISSUE TITLE
Base setup

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#51]
## Overview
Basic build install, configuration, wysiwyg
## Dev [20 hrs]
- [x] Create module structure document for review outlining planned features/modules and what they contain in the Wiki.
  - [Work in progress](https://github.com/thinkshout/bene/wiki/Module-Structure)
- [ ] Remove unnecessary config from the profile and/or bene_core. Site specific config should be set on install to avoid overridden features.
- [ ] WYSIWYG config:
  - [x] Restricted (no editor):
    - [x] Bold/italic/underline/strikethrough
    - [x] Bullets
    - [x] Header styles (h2 through h?)
    - [x] Pull quote style
    - [x] Text alignment options
    - [x] Permissions: staff, admin
  - [x] Basic (CKEditor):
    - [x] Same allowed tags as restricted (with CKEditor buttons) plus:
    - [x] Media embed (configured in #64 and #68)
    - [x] Break
    - [x] Permissions: staff, admin
    - [x] Link button (w/ LinkIt)
  - [x] Full HTML (CKEditor):
    - [x] Same as Basic but don't include the limit allowed tags filter.
    - [x] Permissions: admin
    - [x] Link button (w/ LinkIt)

**Comment by ruscoe** [comment]
For the Basic text format, is there already a CKEditor plugin for the Paragraphs module? I haven't been able to find it.

**Comment by tauno** [comment]
I think this was a mistake - we aren't embedding paragraphs into CKEditor. I think this ticket is done on the dev front for now.
