### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#53]
## Overview
Build and configure basic custom theme (other theming work relies on this)
## Theme [12 hrs]
- [x] Rename theme from `ts_benefit` to `bene_base` or `benefit` or something else without the ts_ name spacing.
- [x] Child theme template to be used to house customizations (fonts, colors, etc) for each client implementation

**Comment by komejo** [comment]
Ready for review in 8.x-1.x - you might have to update and reinstall for the themes to display correctly. Should show the 'Bene Child Theme' .SVG logo.
