### ISSUE TITLE
Basic MailChimp configuration

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#54]
## Overview
The Bene Newsletter functionality is intended to provide a Bene site owner a specific option to subscribe their users to their newsletter. The scenarios we have envisioned are:

1. Simple link to external or internal form for subscribing to the newsletter.
2. Embedded form connected to MailChimp

The block exists currently: /admin/structure/block/manage/benenewslettersignup and has these two options on the block form. The embedded form doesn't currently do anything though as we have not integrated with MailChimp yet. 

The goal of this issue is to integrate MailChimp into Bene, add a simple signup form with minimal fields and embed that form in the newsletter block when the "Embedded Form" is selected. 

Bene base theming for this form would follow this design pattern:
![bene_preview_mode_-_invision](https://user-images.githubusercontent.com/179803/36808620-7688383e-1c7a-11e8-9cd3-737ea7a4207f.png)

## Dev [3 hrs]
Create Mailchimp Signup Block and configure the current Newsletter block to load it. Export all the configurations for the signup block except the MailChimp API key. This will prepare the signup form so that it's ready to go once an API key has been added.

The newsletter block has 3 options: Disabled, External, Embedded Form.

Disabled will keep the existing functionality to remove the sign up block. External will keep the existing functionality for an external signup link. Embedded form will become MailChimp Signup.

When the MailChimp signup is enabled, the block must check for a valid MailChimp API key. If no key is loaded, print a message linking to the MailChimp configuration. 

When the API key is loaded, the Newsletter block should allow you to select a Mailchimp Signup block from a drop down box of all Newsletter Signup blocks. When a block has been selected, display that block to the public facing site.

## Theme [3 hrs]

MailChimp Signup blocks do not support reordering fields. So, the MailChimp Signup block fields will be Email > First Name > Last Name.

**Comment by tauno** [comment]
Not for MVP

**Comment by mshaver** [comment]
Hi @tauno, I'm moving this into the To Do column, as we need at least to have MailChimp installed for WRI launch. It's possible we could wait and complete in a more unified way for the distro since WRI isn't ready for launch just yet, but we'll need sooner than later.

**Comment by mshaver** [comment]
Hi @tauno, I'm assigning back to you since you said you might have bandwidth to look into?

**Comment by mshaver** [comment]
@tauno, nudge, nudge!

**Comment by tauno** [comment]
@Greg-Boggs Let's just use the default ordering of fields from Mailchimp for now. No need to re-order via CSS.

**Comment by Greg-Boggs** [comment]
Got it. Will update the spec.

**Comment by Greg-Boggs** [comment]
This ticket is ready for review.

**Comment by Greg-Boggs** [comment]
I just realized that the h2 font for Bene is smaller than the current p font for the newsletter. This can't be correct. I tried the base size for P, but it's super small. Do we have a style guide for Bene or can I get the sizes for H2 and P?
