### ISSUE TITLE
Primary Nav

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#56]
## Overview
Main Menu. No drop down.

![image](https://user-images.githubusercontent.com/250188/27108381-b7c33718-5051-11e7-98af-fbf174b0aba5.png)

## Dev [hrs]
- [x] Stub out main menu items
- [x] Automate running the migration on install by extending the existing `robo install` command to add running the migration as the next step.
- [x] Set permissions (staff and admin)
  - Administer menus and menu items
## Theme [8 hrs]
- [x] Theme menu items
- [ ] HOLD: Apply special theming to the last item. We should decide how we want to handle this.
- [ ] Active link in mobile menu needs styling fix. Go to /about (after running migration) and open the mobile menu.

<img width="386" alt="screen shot 2017-07-18 at 11 01 09 am" src="https://user-images.githubusercontent.com/250188/28332127-726f71aa-6ba8-11e7-8960-5a6c6297a790.png">

## This ticket is done when:
- [x] Menu items in design appear on a fresh install
- [x] Staff can create, edit, delete menu items.

**Comment by ruscoe** [comment]
Could I get a list of the permissions to set for admin and staff roles?

**Comment by komejo** [comment]
Themed in 8.x-1.x. 
Note: Last menu Item special theming is trivial - I have a button mixin I can apply to menu-item:last-child. I added it in about 5 min.

**Comment by komejo** [comment]
Bumped the last-item theming to the Utility menu to reflect latest designs.

**Comment by tauno** [comment]
Moved to top comment.

**Comment by komejo** [comment]
Fixed in 8.x-1.x.
