### ISSUE TITLE
Log in and Registration

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#58]
## Dev [2 hrs]
- [x] Utilize email registration module for login and user account work.
- [x] Username should be hidden in favor of email through the site (admin forms, registration, user profile, etc.

## Theme [4 hrs]
- [x] Theme login and forgot password forms.

## This ticket is done when:
- [x] Login form items are themed (admin use only)

**Comment by tauno** [comment]
Looks good, can be themed after base theme is done.
