### ISSUE TITLE
Sub Nav

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#59]
## Overview
Interior sub navigation

Design: https://projects.invisionapp.com/d/main#/console/11224218/243833081/preview
Mobile (closed): https://projects.invisionapp.com/d/main#/console/11224218/243833082/preview
Mobile (open): https://projects.invisionapp.com/d/main#/console/11224218/243833084/preview

## Dev [hrs]
- [x] Configure a block to render three components:
  - [x] Breadcrumb without the current page.
  - [x] Current page title (not a link)
  - [x] Child items of the current page, if there are any.
- [x] Place below the title block and before the content block.

## Theme [4 hrs]
- [x] Theme desktop
- [x] Collapse child items on mobile and make the current page title (with down arrow) open up the child items.

## This ticket is done when:
- [x] Pages from the menu structure appear as child links
- [x] A user on mobile can open and close the child links menu

**Comment by ruscoe** [comment]
FYI for theming: I tested breadcrumbs by enabling the Book module and creating a book with a few pages. That was the quickest way I could think of.

**Comment by ruscoe** [comment]
@tauno Any thoughts on handling a child page links situation where "Sub Page 2" is a child of both "Test Page" and "Sub Page 1"?

Only show links directly below the current page?

![screen shot 2017-07-26 at 7 30 11 pm](https://user-images.githubusercontent.com/87952/28651851-3565b94e-7239-11e7-8c3d-6655745f4aa3.png)

![screen shot 2017-07-26 at 7 30 20 pm](https://user-images.githubusercontent.com/87952/28651859-3c029290-7239-11e7-95ca-5b27158162c8.png)

**Comment by ruscoe** [comment]
Pull request #80

**Comment by juliaford** [comment]
@heypaxton this is still not working, the breadcrumb functionality works when you click on a main navigation page but any sub page toggling reverts to a bullet point

**Comment by juliaford** [comment]
<img width="251" alt="screen shot 2017-09-26 at 4 18 44 pm" src="https://user-images.githubusercontent.com/28023410/30888625-6301e008-a2d6-11e7-847a-8083c7d245d1.png">

**Comment by tauno** [comment]
@heypaxton Same as #125? If so let's close one.
