### ISSUE TITLE
Site admin needs to add, edit or delete site users/admins, including their own profile

### ISSUE THREAD

**Issue by tauno** [thinkshout/bene#6]
- [x] Use email address and not username for login
- [ ] Update password
- [ ] Retrieve lost password
- [ ] Invite new users
- [ ] Change permissions for users

**Comment by unclegcb** [comment]
Hm. Features doesn't want to export manually created roles. May need to use ``` \Drupal\user\Entity\Role::create``` to generate the Admin User role during profile install.
