### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#61]
## Dev [4 hrs]
- [x] Two roles: staff and -admin-
- [x] Add "Staff admin" role to distinguish from the super admin role
- [x] Add permissions settings in install hooks for each of the appropriate modules (media related permissions should be set in bene_media_install() for example).

Staff should have content, media (including media browser), menu, alias, and site report related permissions (see FRGK or CORI sites as examples although they might not be perfect yet). Staff admin should just have the addition of administer users for now. Since user can have multiple roles, staff admin should only get additional permissions beyond staff and we'll set those users to have both staff and staff admin roles.

## This ticket is done when:
- [x] Permissions for staff admin are complete
- [x] Permissions for staff are complete

**Comment by tauno** [comment]
Assigning to @ruscoe to setup the basic roles to start. We'll need to spec out the broader set of permissions for the two roles before fully completing this task.

**Comment by ruscoe** [comment]
Roles have been added. Just waiting for permissions.

**Comment by juliaford** [comment]
@tauno please advise on permissions

**Comment by tauno** [comment]
The current Bene Feature bundle configuration is stripping permissions from the exports. We should change that and then re-export Features.

**Comment by juliaford** [comment]
@tauno where are we at with this ticket?

**Comment by ruscoe** [comment]
- [x] Staff permissions
  - [x] Access Media browser pages
  - [x] Access Media browser (Modal) pages
  - [x] Access the Media overview page
  - [x] Create media
  - [x] Delete any media
  - [x] Delete media
  - [x] Update any media
  - [x] Update media
  - [x] View media

**Comment by juliaford** [comment]
@tauno is this ticket done?

**Comment by ruscoe** [comment]
@juliaford I just created a pull request for Tauno's review.
