### ISSUE TITLE
Customizable footer

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#62]
## Overview
Footer block with customizability, social media menu/theming

## Design/UX [hrs]
v4:
[Everything below "Newsletter" block](https://drive.google.com/file/d/0B8YyQKwkd_VuRVpFVndScldqeUk/view) ([mobile](https://drive.google.com/file/d/0B8YyQKwkd_VuVEgtTmw0OHNHLVU/view))

## Dev [6 hrs]
- [x] Edit the social media block, and rename it to be the "footer" block. Rename module, etc.
- [x] Make block configurable with fields:
  - [x] Address field (text area, plaintext)
  - [x] Contact Phone field (html 5 tel) 
  - [x] Contact Email field (html 5 email)
  - [x] Copyright field (text) (circle-c will be added automatically)
  - [x] Leave social configuration options as-is
- [x] Add Footer Menu preview at top of form: shows footer menu laid out like in display
- [x] Add help text "To customize the menu in the footer, click here" with target=blank link to footer menu edit page (at the top)
- [x] Block render function with classes for themeing
- [x] Place block in footer by default sitewide with weight = 100
- [x] Create default footer configuration using placeholder values
- [x] default footer menu content (add to menu links migration) with 3 items and one second-level item (match wireframes)

## Theme [8 hrs]
- [x] Add block to footer region in install (remove existing footer menu)
- [x] Theme footer footer various responses.
- [x] Theme social icons (will be configurable per-site - at least colors)
- [x] Test combinations of including or not including different pieces of info

## This ticket is done when:
- [x] Site install includes a footer with default values displayed
- [x] Site editor can click edit on the footer and remove, add, or edit all elements of footer in the designs

**Comment by tauno** [comment]
The latest designs show some additional text (Find us on Google Maps and Donate/Volunteer/Shop hours). Perhaps we need two additional WYSIWYG text fields that can be used for these flexible purposes.

**Comment by komejo** [comment]
I think this task it pretty much phase1 complete and ready for QA. Might be a good idea to put certain types of feedback in a phase2 task?
