### ISSUE TITLE
Basic Page Content Type

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#65]
## Overview
Simple content type with title, paragraphs content area, one image

Design: https://drive.google.com/file/d/0B8YyQKwkd_VubWNJVzdUMUY4Nzg/view

## Dev [hrs]
- [x] Remove body field
- [x] Header image (#63)
- [x] Add excerpt field (wysiwyg) to be used as the teaser.
- [x] No commenting or author information.

## Theme [hrs]
- [x] Intro content
- [x] Header theming in #63 

## This ticket is done when:
- [x] Pages can be created with optional header image, excerpt and introduction.
- [x] Permissions are configured for staff and admins to create, edit, delete, etc. pages.

**Comment by tauno** [comment]
@unclegcb with paragraphs (#70) is the plan to remove the body field? If so we'll need to specify to add a teaser field. The Thunder distro has a decent approach that includes a teaser image for teasers (duh) but also FB and Twitter shares.

![Thunder Article Edit](https://cloud.githubusercontent.com/assets/250188/26697468/04f6edb6-46c7-11e7-9c54-5ccaeba62eb3.png)

**Comment by unclegcb** [comment]
I think so. The other option is to let the Body operate as the "first paragraph", but that just seems confusing.

**Comment by tauno** [comment]
Header image to be handled in #63

**Comment by tauno** [comment]
- [x] Add Editor profile for Restricted input format (bold, italic, linkit, unlink, headings)
- [x] Add intro field (summary + long text) using Restricted input format
- [x] Remove excerpt field

**Comment by juliaford** [comment]
@komejo do you have a sense of how much more time you need for this ticket?

**Comment by komejo** [comment]
@juliaford Just finished it up today!
