### ISSUE TITLE
Wysiwyg Media

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#68]
## Design/UX [hrs]
- [x] Provide image / video dimensions for each breakpoint
- [x] Find/create image to use for the embed icon

## Dev [4 hrs]
- [x] Configure Embed button to allow embedding all bundles of media items with the "Embed" view mode.
- [x] Configure embedding display mode for: images, videos, documents

## Theme [8-14 hrs]
- [x] Create necessary image styles for embed view mode of images
- [ ] Theme content width image
- [ ] Theme content width video (test with YouTube and Vimeo)
- [ ] Theme embedded document

## This ticket is done when:
- [x] Admin and Staff can embed media in basic page
- [ ] Embedded images are responsive

**Comment by tauno** [comment]
@komejo / @unclegcb Any concerns about supporting full width (wider than the content) within an embed? If that's likely to be challenging it might be simpler to add image and video paragraph types for the full width functionality.

**Comment by komejo** [comment]
If the theme supports full width, having in image inside an embed shouldn't add too much additional complexity - we'd just need the embed the have a 'full-width' class at the top level, which we can probably do with a template or a template-preprocess.

**Comment by tauno** [comment]
Then the question is does full width make sense as an embed or should it be a paragraph type for simplicity for the editor. So: image/video embed = content width and paragraph image/video = full width. This avoids the user needing to choose a view mode (and understand the difference between full width and content width) to use when inserting the media item.

**Comment by vickibrown** [comment]
@tauno I think that makes sense, unless full-width is also available as part of the WYSIWYG, which I'd assume is not the case.

**Comment by juliaford** [comment]
https://docs.google.com/spreadsheets/d/1deOgeSDhZNrBZaaRohJNFF-QgBaiICEuxmIuSiET0Ag/edit#gid=0

**Comment by juliaford** [comment]
Hey @tauno @ruscoe @mshaver @heypaxton can we make the wysiwyg default, or only, show the full html text format to the user? It is confusing otherwise.
