### ISSUE TITLE
Newsletter sign up 

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#69]
## Overview
Signup form block with option to link to external system or embed another block (which can include a signup form).

## Design/UX [hrs]
v4:
[Newsletter block](https://drive.google.com/file/d/0B8YyQKwkd_VuRVpFVndScldqeUk/view) ([mobile](https://drive.google.com/file/d/0B8YyQKwkd_VuVEgtTmw0OHNHLVU/view))

## Dev [4 hrs]
- [x] Create a custom block called "Newsletter Signup" ([simpler example](https://github.com/thinkshout/teaching-tolerance/blob/develop/web/modules/custom/tt_blocks/src/Plugin/Block/NewsletterSignupFooterBlock.php))
- [x] Add "Style" radio selector with 3 options: "Disabled"; "External"; "Embedded Form" -- default to "External"
- [x] Optional: "Title" text field (default: "Sign up for our Newsletter") 
- [x] Optional: "Text" textarea field (default: "Receive updates about what we are doing")
- [x] Add "External Link Settings" field group
  - [x] Hide unless "Style" set to "External"
  - [x] Link field
  - [x] Link Label field
- [ ] Block display function
  - [ ] Use "Style" setting to determine what to display:
    - [x] "Disabled" -- empty
    - [x] "External" -- Title, Text, and a button to the external link with the link button label
    - [ ] HOLD: "Embedded" -- Title, Text, and the selected block
- [x] Place Newsletter block in footer with weight of 90, sitewide, by default, with placeholder configuration

HOLD:
- [ ] Add "Embedded Form" field group
  - [ ] Hide unless "Style" set to "embedded"
  - [ ] Form Block field: Provide an entity selector field that can select a Block. Description "Select the block to use as your Newsletter Signup form"

## Theme [4 hrs]
- [x] Place in footer with correct weight on install
- [x] Theme the form in "External" mode
- [x] If Title and/or Text are included, theme Link and Label as a button
- [x] If no Title or Text, theme Link / Label as a big link

HOLD:
- [ ] Theme the form in "Embedded" mode, using an embedded Mailchimp block
- [ ] ensure Mailchimp block display works for multiple mailchimp signup block configurations (don't rely on a block machine name -- may require customizations in Block Display behavior in Dev)

## This ticket is done when:
- [ ] Anonymous user is sent to newsletter subscribe form off site (if configured for External)
- [ ] Disabled Footer block does not break site theming

HOLD:
- [ ] Anonymous user can subscribe to MailChimp (if configured for Mailchimp)

**Comment by ruscoe** [comment]
There are a couple of thing on hold, but this could probably still be themed.
