### ISSUE TITLE
Site admin needs to add, edit or delete organizational social profile links

### ISSUE THREAD

**Issue by tauno** [thinkshout/bene#7]
- [ ] Create theme-specific icons
- [ ] Add to footer block by default

**Comment by nrackleff** [comment]
- [ ] Generate bene_social module
- [ ] Generate social block plugin with url fields for facebook, google, instagram, linkedin, pinterest, tumblr, twitter and youtube.
- [ ] Block output to be links to each service based on form input.
- [ ] Provide SVGs for each of the above services. (Use http://changeforanimals.humanesociety.org/)
- [ ] Place the block in the footer region

**Comment by nrackleff** [comment]
Progress. I’ve got a social media links block created via custom module. It has configuration for eight services and outputs them in the footer. See attached. I’m heading our for a walk. If I get hit by a bus or anything, the work is in the social-profile-links branch of https://github.com/thinkshout/bene. I just borrowed the svg icons from human society site. We will need to have new ones in the round format for our theme.
![social-block](https://cloud.githubusercontent.com/assets/777368/18570559/d830659c-7b5f-11e6-9c44-0265e0fb02d6.png)

**Comment by unclegcb** [comment]
Design to provide icon assets for use with theme, then assign back to me.
