### ISSUE TITLE
Title field for tiles paragraph 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#82]
## Overview

We need an optional title field to go above the tiles themselves.

## Dev [hrs]
- [x] Add a text field (single line) to the Tiles paragraph type. Optional.

## Theme [hrs]
- [x] Theme it!

## This ticket is done when:
- [x] Staff user can optionally add a title to a set of tiles
- [x] Title is themed in all sizes.

**Comment by komejo** [comment]
Done and checked in, though Circle seems a tad unresponsive.
