### ISSUE TITLE
Polish Notes

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#89]
## Dev
- [ ] media browser/upload/ doesn't save selection on enter
- [ ] The ability to edit button text in the RT paragraph type  after it has been hyperlinked is hard to work with. The cursor becomes a hovering fist and wants to click on the link and makes getting back into the text to edit hard. 

## Theme
- [x] intro text is going full width and needs to have a max width applied 
- [x] also need a max width on header region
- [x] header image loses it's image and goes back to a color at a certain width 
- [ ] feature paragraph block responds the same way as header image at widest breakpoint
- [x] header image needs to be resized according to image specs to align with designs
- [ ] list spacing issues
<img width="468" alt="bene-list-spacing-00" src="https://user-images.githubusercontent.com/179803/29693905-2b6dd6f4-88ed-11e7-8b53-3c5ed821eb45.png">

**Comment by juliaford** [comment]
Moved to top

**Comment by juliaford** [comment]
@tauno @ruscoe can we add the ability to left/right/center align in wysiwyg fields?

**Comment by juliaford** [comment]
@komejo @heypaxton for tiles content type, if I upload a verticle photo it rotates it sideways here, can it just scale appropriately instead? See my pup here: http://dev-bene.pantheonsite.io/node/8

**Comment by tauno** [comment]
@juliaford and @mshaver where are we at with this list of polish items?

**Comment by mshaver** [comment]
@tauno, I think we need to run through these items to confirm.
