### ISSUE TITLE
News

### ISSUE THREAD

**Issue by tauno** [thinkshout/bene#92]
## Overview
Content type and basic listing.

## Design/UX [hrs]
- [ ] Design news landing page
- [ ] Full page news design

## Dev [8 hrs]

- [x] News content type
- [x] View
  - [x] Display content of type "news"
  - [x] Display news in reverse chronological order
  - [x] Sort by custom publish date
  - [x] Search by event title?

## Theme [8 hrs]
- [x] Listing page - Follow design although there are no sort options and instead there are filters for keyword and date range
  - [x] Filter form
  - [x] Teasers
  - [x] Pager
- [x] Theme full view of news node

**Comment by vickibrown** [comment]
@tauno Do you need a separate design for this from the Events listing?

**Comment by mshaver** [comment]
@vickibrown, I don't think we need another design. We'll match to the events design.

**Comment by mshaver** [comment]
@tauno, handing this over to you to spec and hand over to @ruscoe. I'm guessing it's an exact match of events, just with News in there.

**Comment by heypaxton** [comment]
@tauno can we update the labels for the date range fields to be "start" and "end"?

**Comment by tauno** [comment]
Labels have been updated.
