### ISSUE TITLE
Child Theme Estimates

### ISSUE THREAD

**Issue by heypaxton** [thinkshout/bene#94]
## Overview
This issue contains estimates for child theme customizations. This issue can be branched out into other issues.

### Home Page
- Logo [1 hrs]
- Navigation [4 hrs]
- Banner: [4 hrs]
  - option for text over/below image on small screen
- Feature CTA: [4 hrs]
  - option for gradient customization
  - options for text over / below image on small screen
- Tiles [2 hrs]
- Buttons [1 hrs]
- Footer [2 hrs]

### Inner Pages
- Banner [4 hrs]
- Subnav: [3 hrs]
  - color [1 hrs]
  - Menu position [2 hrs]
- Callout Text [2 hrs]
- Wysiwyg Styles [4 hrs]

### Views
- Upcoming Events [4 hrs]
  - Filters [2 hrs]
  - List item (with or without image) [2 hrs]
- Events [4 hrs]
  - Filters [2 hrs]
  - Cards [2 hrs]
- Pagination [1 hrs]
## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mshaver** [comment]
Thanks for putting this together @heypaxton! Looks good for sure. I changed a few of the names to match the language we've been using, but otherwise I think you covered everything.
