### ISSUE TITLE
FRGK Child Theme: Inner Page

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#97]
## Theme
- [ ] Banner [4 hrs]
- [ ] Subnav: [3 hrs]
- [ ] color [1 hrs]
- [ ] Menu position [2 hrs]
- [ ] Callout Text [2 hrs]
- [ ] Wysiwyg Styles [4 hrs]

## Polish
- [ ] background-image for feature block overwriting the image upload
![free_geek-p-image](https://user-images.githubusercontent.com/179803/30353083-b06d9ade-97d8-11e7-98d7-3e6a614ce4af.png)

**Comment by mshaver** [comment]
@heypaxton, I'm adding polish items to this ticket when I find them.

**Comment by juliaford** [comment]
@heypaxton @tauno from FRGK: 
Question: I've been playing around with adding content to a sample page this morning. I noticed that the rich text content block doesn't have the ability to toggle the source HTML, while the introduction block does allow that toggle option. Is this just a bug that's currently being worked out?

The reason I'm asking is that some of our content blocks will need headers down to h4, and I'm unable to access headers past h3 in the rich text formatting menu.

**Comment by mshaver** [comment]
@juliaford, I've created an issue for the above comment already: #106
